##############
### dev
##############

server:
 port: 8080 

spring:
  cloud:
    stream:
      function:  ## 반드시 있어야 함 
        definition: boardCreate;boardUpdate;boardDelete
      kafka:
        default:
           consumer:
             ack-mode: MANUAL_IMMEDIATE
        binder:
          brokers:
          - sa-cluster-kafka-bootstrap:9092
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              mechanism: SCRAM-SHA-512
              jaas:
                config: org.apache.kafka.common.security.scram.ScramLoginModule required username="order-user" password="Kfix1IkttbDa";
            
            ssl:
              truststore.location: classpath:/truststore.jks
              truststore.type: JKS
              truststore.password: new1234


      bindings:           
        boardCreate-in-0:          
          destination: sa-app-order-board-create
          group: order-board-group        
        boardUpdate-in-0:
          destination: sa-app-order-board-update
          group: order-board-group
        boardDelete-in-0:
          destination: sa-app-order-board-delete
          group: order-board-group
